# Search for "Norway" using REGEX

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT * WHERE {
  ?c skos:prefLabel ?pl .

  FILTER (REGEX(?pl, "Norway"))
}

# should get 3 results in a long time
